---
- :method: :person_attributes
  :constant: Export::Tabular::People::PeopleAddress
  :wagon: swb
  :source_file: hitobito/app/domain/export/tabular/people/people_address.rb
  :patch_file: hitobito_swb/app/domain/swb/export/tabular/people/people_address.rb
  :patch_file_line: 9
- :method: :cancel_all_invoices
  :constant: InvoiceListsController
  :wagon: swb
  :source_file: hitobito/app/controllers/invoice_lists_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/invoice_lists_controller.rb
  :patch_file_line: 11
- :method: :index
  :constant: JsonApi::EventsController
  :wagon: swb
  :source_file: hitobito/app/controllers/json_api/events_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/json_api/events_controller.rb
  :patch_file_line: 13
- :method: :filter_entries
  :constant: PeopleController
  :wagon: swb
  :source_file: hitobito/app/controllers/people_controller.rb
  :patch_file: hitobito_swb/app/controllers/swb/people_controller.rb
  :patch_file_line: 20
- :method: :full_label
  :constant: PersonDecorator
  :wagon: swb
  :source_file: hitobito/app/decorators/person_decorator.rb
  :patch_file: hitobito_swb/app/decorators/swb/person_decorator.rb
  :patch_file_line: 11
- :method: :to_s
  :constant: Role
  :wagon: swb
  :source_file: hitobito/app/models/role.rb
  :patch_file: hitobito_swb/app/models/swb/role.rb
  :patch_file_line: 27
