#  Copyright (c) 2012-2025, Swiss Badminton. This file is part of
#  hitobito_swb and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_swb.


# Settings relevant for the hitobito_swb wagon
# Overrides settings from the main application
application:
  logo:
    image: logo-white.svg
    width: 200
    height: 68
    background_color: "#931D1B"
  languages:
    de: Deutsch
    en: English
    fr: Français
    it: Italiano

  # non UI languages for assigning to person#language
  # additional_languages:
  #   en: Englisch
phone_number:
  predefined_labels:
    - --
    - mobile
    - landline
people:
  public_profile: https://www.example.com/player/%d

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito-swb@puzzle.ch

groups:
  yearly_budgets:
    - ..5000
    - 5000..10000
    - 10000..15000
    - 15000..

invoices:
  membership:
    enabled: true
    recipient:
      layer: Group::Verein
      roles:
        - Group::Verein::Finanzen
        - Group::VereinVorstand::Kassier
        - Group::VereinVorstand::Praesident
    fees:
      - name: senior
        unit_cost: 100
        roles:
          - Group::VereinSpieler::Aktivmitglied
          - Group::VereinSpieler::Passivmitglied
          - Group::VereinSpieler::Lizenz
          - Group::VereinSpieler::LizenzPlus
          - Group::VereinSpieler::LizenzNoRanking
          - Group::VereinSpieler::Vereinigungsspieler
      - name: junior
        unit_cost: 50
        roles:
          - Group::VereinSpieler::LizenzPlusJunior
          - Group::VereinSpieler::JuniorU15
          - Group::VereinSpieler::JuniorU19
